Repository Curtismn87/test-react-app, pull requests merged in 2020-06, with the labels that each got.

#4 Added bootstrap and some styling
  package.json
  src/App.css
  src/App.js
Labels: enhancement

#5 Changed display back to name
  src/App.js
Labels: invalid

#6 Change class to className
  src/App.js
Labels: bug

#7 updated API call
  src/App.js
Labels: enhancement

#10 Breakout into components
  package.json
  src/App.js
  src/components/USDA-API/API-caller.js
  src/config/api-urls.json
  src/pages/Home.js
  yarn.lock
Labels: enhancement
